# Generated by Django 6.1 on 2026-08-22 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
