# Generated by Django 6.1 on 2026-08-27 16:44

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_invoice_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.logo_upload_path),
        ),
    ]
