# Generated by Django 6.1 on 2026-08-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_service_booking_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
