# Generated by Django 6.1 on 2026-08-31 18:12

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_workspace_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.service_photo_upload_path),
        ),
    ]
