# Generated by Django 6.1 on 2026-09-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_service_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='currency',
            field=models.CharField(default='EUR', max_length=5),
        ),
    ]
