# Generated by Django 6.1 on 2026-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_workspace_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
