# Generated by Django 6.1 on 2026-09-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_service_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_series', to='portal.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_series', to='portal.service')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_series', to='portal.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='portal.recurringseries'),
        ),
    ]
