# Generated by Django 6.1 on 2026-09-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_recurringseries_booking_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
