# Generated by Django 6.1 on 2026-09-08 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_user_staff_workspace_alter_user_role_teaminvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_clients', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('max_team_members', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
            ],
            options={
                'ordering': ['price_per_month'],
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='portal.subscriptionplan'),
        ),
    ]
