# Generated by Django 6.1 on 2026-09-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_seed_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='brand_color',
            field=models.CharField(default='#2563eb', help_text='Hex color, e.g. #2563eb', max_length=7),
        ),
    ]
