# Generated by Django 6.1 on 2026-09-08 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_workspace_brand_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many identical units exist, e.g. 3 chairs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(blank=True, related_name='resources', to='portal.service')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='portal.workspace')),
            ],
        ),
    ]
