# Generated by Django 6.1 on 2026-09-08 16:19

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=portal.models.resource_photo_upload_path),
        ),
    ]
