# Generated by Django 6.1 on 2026-09-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_resource_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_bookings', to='portal.resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Default booking length when this resource is booked directly, without a service. Up to 1440 for a full 24-hour slot.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='portal.service'),
        ),
    ]
