# Generated by Django 6.1 on 2026-09-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_booking_resource_resource_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for a direct booking of this resource, optional.', max_digits=10, null=True),
        ),
    ]
