# Generated by Django 6.1 on 2026-09-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_late_cancellation',
            field=models.BooleanField(default=False, help_text="Set when cancelled inside the service's cancellation_notice_hours window, for the owner to see at a glance whether the late-cancellation fee applies."),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Amount required at booking time (deposit or full price), snapshotted from the service's policy so a later price change never changes what was already owed.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='cancellation_notice_hours',
            field=models.PositiveIntegerField(default=24, help_text='Minimum hours before the appointment a client can cancel or reschedule without triggering the late cancellation fee.'),
        ),
        migrations.AddField(
            model_name='service',
            name='deposit_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Percent of price required as a deposit at booking time. Only used when payment_requirement is 'deposit'.", null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='late_cancellation_fee_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Percent of price treated as a late-cancellation/no-show fee when cancelled inside the notice window. Blank = no fee - any deposit paid is simply refundable.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='payment_requirement',
            field=models.CharField(choices=[('none', 'No payment at booking'), ('deposit', 'Deposit required'), ('full', 'Full payment required')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No-show')], default='confirmed', max_length=20),
        ),
    ]
