# Generated by Django 6.1 on 2026-09-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_booking_is_late_cancellation_booking_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set by the send_booking_reminders management command once a reminder email has gone out, so the same booking is never reminded twice.', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='reminder_hours_before',
            field=models.PositiveIntegerField(default=24, help_text='How many hours before an appointment send_booking_reminders should email a reminder (BOOK-59).'),
        ),
    ]
