# Generated by Django 6.1 on 2026-09-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_booking_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 code driving the currency picker (see portal.currencies) - blank for workspaces created before this field existed.', max_length=2),
        ),
    ]
