# Generated by Django 6.1 on 2026-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_workspace_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', help_text="Connected Stripe Standard account (acct_...) this workspace's owner linked via OAuth (see views.WorkspaceStripeConnectCallbackView). Client checkout sessions are created directly on this account so payments land in the owner's own Stripe balance, not the platform's. Blank means the owner hasn't connected one yet - checkout is blocked until they do.", max_length=32),
        ),
    ]
