# Generated by Django 6.1 on 2026-09-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_workspace_stripe_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "MTN Mobile Money", "Orange Money", "Bank transfer".', max_length=100)),
                ('account_details', models.TextField(help_text='Whatever the client needs to send money directly - phone number, account number, account holder name, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='portal.workspace')),
            ],
        ),
    ]
