# Generated by Django 6.1 on 2026-09-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Hides an inactive client from the default list (CLIENT-04) without deleting their history.'),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Owner/staff-only notes and preferences about this client (CLIENT-05) - never exposed to the client themselves.'),
        ),
    ]
