# Generated by Django 6.1 on 2026-09-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_client_is_archived_client_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('contract', 'Contract'), ('deliverable', 'Deliverable'), ('invoice', 'Invoice'), ('reference', 'Reference'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='is_private',
            field=models.BooleanField(default=False, help_text="Owner/staff-only visibility (DOC-06) - hidden from the client entirely, not just non-downloadable. Only owner/staff can set this; a client's own uploads are always visible to the workspace (see DocumentViewSet)."),
        ),
    ]
