# Generated by Django 6.1 on 2026-09-10 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_message_attachment_message_attachment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staff',
            field=models.ForeignKey(blank=True, help_text="Which team member is handling this appointment (TEAM-04/TEAM-05, SEARCH-04) - manually assigned by owner/staff for now; not yet factored into availability, so assigning someone doesn't block their calendar elsewhere.", limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_staff',
            field=models.ManyToManyField(blank=True, help_text="Team members responsible for this client (TEAM-04) - a staff member's 'my clients' view, and by extension their 'my projects' view, is derived from this rather than a separate per-project assignment, since every project in this app already hangs off exactly one client.", limit_choices_to={'role': 'staff'}, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='staff',
            field=models.ManyToManyField(blank=True, help_text='Team members qualified to perform this service (TEAM-05). Empty means any team member can - the field is informational for now (BOOK-04/10/19, staff selection in the booking flow itself, is a separate follow-up).', limit_choices_to={'role': 'staff'}, related_name='bookable_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
