# Generated by Django 6.1 on 2026-09-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_booking_staff_client_assigned_staff_service_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='instructions',
            field=models.TextField(blank=True, default='', help_text='What the client should prepare or know before the appointment (BOOK-08), shown to them when booking.'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether this service is conducted virtually (BOOK-07). meeting_link is only meaningful when this is set.'),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Where an in-person appointment takes place (BOOK-06), e.g. an address or room name.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='meeting_link',
            field=models.URLField(blank=True, default='', help_text='Video call link shared with the client once booked (BOOK-07), e.g. a Zoom or Google Meet URL.'),
        ),
    ]
