# Generated by Django 6.1 on 2026-09-11 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_service_instructions_service_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='staff',
            field=models.ForeignKey(blank=True, help_text="Left blank, this is the workspace's default availability. Set to a team member, it overrides the default for that person only (TEAM-05/BOOK-10) - AvailabilityView falls back to the workspace default rows when a staff member has none of their own.", limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to=settings.AUTH_USER_MODEL),
        ),
    ]
