# Generated by Django 6.1 on 2026-09-11 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_workinghours_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='buffer_after_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Recovery time required after this service ends (BOOK-13) - blocks the slot immediately after a booking.'),
        ),
        migrations.AddField(
            model_name='service',
            name='buffer_before_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Prep time required before this service starts (BOOK-13) - blocks the slot immediately prior to a booking, even if it would otherwise fit.'),
        ),
        migrations.AddField(
            model_name='service',
            name='max_advance_days',
            field=models.PositiveIntegerField(blank=True, help_text='Furthest in the future this service can be booked (BOOK-15). Blank = no limit.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='max_bookings_per_day',
            field=models.PositiveIntegerField(blank=True, help_text="Caps total confirmed bookings of this service on any single day (BOOK-16), regardless of who's assigned. Blank = no limit.", null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='max_bookings_per_week',
            field=models.PositiveIntegerField(blank=True, help_text='Caps total confirmed bookings of this service within any calendar week (BOOK-16, Monday-Sunday). Blank = no limit.', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='min_notice_hours',
            field=models.PositiveIntegerField(default=0, help_text='How many hours in advance a booking must be made (BOOK-14). 0 = bookable right up to the start time.'),
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, help_text="Blank blocks the whole workspace (a holiday); set to block only that team member's own calendar.", limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='portal.workspace')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
