# Generated by Django 6.1 on 2026-09-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_service_buffer_after_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='public_booking_enabled',
            field=models.BooleanField(default=False, help_text="Whether /book/<slug> (PublicBookingView, BOOK-26/30) is reachable by anyone with the link, letting a guest book without an account (BOOK-21). Off by default - an owner opts in once they're ready to share it."),
        ),
    ]
