# Generated by Django 6.1 on 2026-09-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_workspace_public_booking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='custom_answers',
            field=models.JSONField(blank=True, default=dict, help_text="BOOK-69/70/71: this service's ServiceQuestion answers at booking time, keyed by question id as a string (e.g. {'3': 'Curly'}) so the owner can review them before the appointment."),
        ),
        migrations.CreateModel(
            name='ServiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Short answer'), ('choice', 'Multiple choice')], default='text', max_length=10)),
                ('choices', models.CharField(blank=True, default='', help_text="Comma-separated options. Only used when question_type is 'choice'.", max_length=500)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portal.service')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_questions', to='portal.workspace')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
