# Generated by Django 6.1 on 2026-09-11 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_booking_custom_answers_servicequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='read_by',
            field=models.ManyToManyField(blank=True, help_text="NOTIF-01: who has already seen this entry in their notification bell. Per-viewer, since a workspace can have several staff - one reading it shouldn't mark it read for everyone else.", related_name='read_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='muted_notification_categories',
            field=models.JSONField(blank=True, default=list, help_text='NOTIF-02: which notification categories (see portal.activity.NOTIFICATION_CATEGORIES) this user has turned off in their notification bell. Empty = notified about everything.'),
        ),
    ]
