# Generated by Django 6.1 on 2026-09-15 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_activity_read_by_user_muted_notification_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedtime',
            name='block_type',
            field=models.CharField(choices=[('other', 'Other'), ('holiday', 'Holiday'), ('personal', 'Personal'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('repair', 'Repair'), ('private_use', 'Private use')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='Set to block only this resource (maintenance, cleaning, repair, private use) rather than a person or the whole workspace.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='portal.resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='booking_buffer_after_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Also used as cleaning/turnover time between reservations.'),
        ),
        migrations.AddField(
            model_name='resource',
            name='booking_buffer_before_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='How many people/things one unit holds, e.g. 8 seats in a meeting room. Distinct from quantity (how many identical units exist). Used when capacity_mode=SHARED.', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='capacity_mode',
            field=models.CharField(choices=[('exclusive', 'Exclusive (one booking per unit)'), ('shared', 'Shared (multiple bookings up to capacity)')], default='exclusive', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Workspace-defined grouping label, e.g. "Deluxe rooms" or "Power tools".', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='custom_type',
            field=models.CharField(blank=True, default='', help_text='Free-text label when type=CUSTOM, e.g. "Golf cart" or "Sauna".', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='extra_rules',
            field=models.JSONField(blank=True, default=dict, help_text="Escape hatch for resource-specific rules that don't warrant their own column yet."),
        ),
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Free-text location for now (a first-class Location entity is a later phase).', max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='max_advance_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='max_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='min_booking_notice_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='min_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='pricing_mode',
            field=models.CharField(choices=[('none', 'None'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('nightly', 'Nightly'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('per_use', 'Per use'), ('custom', 'Custom')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='reservation_mode',
            field=models.CharField(choices=[('booking', 'Via service only'), ('reservation', 'Direct reservation'), ('rental', 'Rental')], default='reservation', help_text="BOOKING: only reservable as part of a service. RESERVATION: reservable directly (today's behavior). RENTAL: reservable directly with rental-lifecycle tracking (deposits, check-in/out, overdue).", max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('blocked', 'Blocked'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='available', help_text='Only BLOCKED/MAINTENANCE/CLEANING/INACTIVE/RETIRED are authoritative and exclude this resource from availability and new reservations. Retire a resource by setting this rather than deleting it, to keep its reservation history intact.', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('chair', 'Chair'), ('table', 'Table'), ('car', 'Car'), ('van', 'Van'), ('hotel_room', 'Hotel room'), ('meeting_room', 'Meeting room'), ('studio', 'Studio'), ('desk', 'Desk'), ('office', 'Office'), ('equipment', 'Equipment'), ('machine', 'Machine'), ('court', 'Court'), ('field', 'Field'), ('boat', 'Boat'), ('bike', 'Bike'), ('parking_space', 'Parking space'), ('room', 'Room'), ('facility', 'Facility'), ('other', 'Other'), ('custom', 'Custom')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='ResourceAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='portal.resource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_availability', to='portal.workspace')),
            ],
            options={
                'verbose_name_plural': 'resource availability',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('combined_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resources', models.ManyToManyField(blank=True, related_name='groups', to='portal.resource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_groups', to='portal.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRentalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_unit', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('nightly', 'Nightly'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('min_rental_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('max_rental_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit_required', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_fee_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allow_recurring', models.BooleanField(default=False)),
                ('cancellation_notice_hours', models.PositiveIntegerField(default=0)),
                ('reschedule_notice_hours', models.PositiveIntegerField(default=0)),
                ('extra_rules', models.JSONField(blank=True, default=dict)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_policy', to='portal.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('alternative', 'Alternative')], default='required', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Units of the resource consumed - used for EXCLUSIVE capacity math against Resource.quantity.')),
                ('party_size', models.PositiveIntegerField(blank=True, help_text='People/slots consumed - used for SHARED capacity math against Resource.capacity.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_reservations', to='portal.booking')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='portal.resource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_reservations', to='portal.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('booking', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='ResourceRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('overdue', 'Overdue'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('deposit_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('held', 'Held'), ('refunded', 'Refunded'), ('forfeited', 'Forfeited')], default='not_required', max_length=20)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('condition_notes_out', models.TextField(blank=True)),
                ('condition_notes_in', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='portal.booking')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recurring_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_rentals', to='portal.recurringseries')),
                ('resource_reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='portal.resourcereservation')),
            ],
        ),
        migrations.CreateModel(
            name='BookingResourceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_charges', to='portal.booking')),
                ('resource_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='portal.resourcereservation')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceResourceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('alternative', 'Alternative')], default='required', max_length=20)),
                ('alternative_group', models.CharField(blank=True, default='', help_text='Rows sharing a non-blank group + requirement_type=ALTERNATIVE are satisfied by reserving any one of them.', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requirements', to='portal.resource')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requirements', to='portal.service')),
            ],
            options={
                'unique_together': {('service', 'resource')},
            },
        ),
    ]
