# Generated by Django 6.1 on 2026-09-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_resource_backfill_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restricted',
            field=models.BooleanField(default=False, help_text="TEAM-02: only meaningful for role=STAFF. False (the default) is today's behavior unchanged - this team member sees the whole workspace. True scopes them, everywhere, to only the clients (and everything hanging off those clients - projects, documents, messages, invoices, bookings) they're listed in Client.assigned_staff for - see permissions.staff_scope()."),
        ),
    ]
