# Generated by Django 6.1 on 2026-09-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_user_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_bookings_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_projects',
            field=models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_storage_mb',
            field=models.PositiveIntegerField(blank=True, help_text='Blank = unlimited. Documents + message attachments combined, across every project in the workspace.', null=True),
        ),
    ]
