# Generated by Django 6.1 on 2026-09-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_seed_plan_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Free-text fallback - prefer location_ref once the workspace has real Locations.', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Where an in-person appointment takes place (BOOK-06), e.g. an address or room name. Free-text fallback - prefer location_ref once the workspace has real Locations.', max_length=255),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Hides a closed/retired location from booking flows without deleting its history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='portal.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Set to block only this location (e.g. closed for a holiday, renovation, or private event) rather than a person, a resource, or the whole workspace.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='portal.location'),
        ),
        migrations.AddField(
            model_name='resource',
            name='location_ref',
            field=models.ForeignKey(blank=True, help_text='A structured Location, superseding the free-text `location` field above when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='portal.location'),
        ),
        migrations.AddField(
            model_name='service',
            name='location_ref',
            field=models.ForeignKey(blank=True, help_text='A structured Location, superseding the free-text `location` field above when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='portal.location'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='location',
            field=models.ForeignKey(blank=True, help_text="Only meaningful when `staff` is blank - a location's own default hours, which a service linked to that location falls back to when its staff member has no personal hours, before falling further back to the workspace-wide default (staff blank, location blank).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='portal.location'),
        ),
    ]
